# Generated by Django 5.1.6 on 2025-03-05 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2048)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateField(default=datetime.date(2025, 3, 6))),
                ('poster', models.ImageField(default='images/default.jpg', upload_to='images/')),
            ],
        ),
    ]
