# Generated by Django 5.1.6 on 2025-03-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='image/default.jpg', upload_to='image/'),
        ),
    ]
