# Generated by Django 5.1.6 on 2025-03-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_post_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.ImageField(default='image/default.png', upload_to='image/'),
        ),
    ]
