# Generated by Django 5.1.6 on 2025-03-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_image_post_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.ImageField(default='images/d.jepg', upload_to='images/'),
        ),
    ]
