# Generated by Django 5.1.6 on 2025-03-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_post_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='img/default.jpg', upload_to='img/'),
        ),
    ]
