# Generated by Django 5.1.6 on 2025-03-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='media/images/default.png', upload_to='media/images/'),
        ),
    ]
